# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x8f\x03\n\x07Message\x12&\n\x08msg_type\x18\x01 \x01(\x0e\x32\x14.Message.MessageType\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\x12\x12\n\nlog_length\x18\x04 \x01(\x05\x12\x15\n\rlast_log_term\x18\x05 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x06 \x01(\x05\x12\x15\n\rprev_log_term\x18\x07 \x01(\x05\x12\x1a\n\x07\x65ntries\x18\x08 \x03(\x0b\x32\t.LogEntry\x12\x15\n\rleader_commit\x18\t \x01(\x05\x12\x0b\n\x03key\x18\n \x01(\t\x12\r\n\x05value\x18\x0b \x01(\t\"\x94\x01\n\x0bMessageType\x12\x0e\n\nSetRequest\x10\x00\x12\x0e\n\nGetRequest\x10\x01\x12\x0f\n\x0bVoteRequest\x10\x02\x12\x10\n\x0cVoteResponse\x10\x03\x12\x0e\n\nLogRequest\x10\x04\x12\x0f\n\x0bLogResponse\x10\x05\x12\x11\n\rAppendEntries\x10\x06\x12\x0e\n\nForwardMsg\x10\x07\"%\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2.\n\x08RaftNode\x12\"\n\x0eReceiveMessage\x12\x08.Message\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=15
  _globals['_MESSAGE']._serialized_end=414
  _globals['_MESSAGE_MESSAGETYPE']._serialized_start=266
  _globals['_MESSAGE_MESSAGETYPE']._serialized_end=414
  _globals['_LOGENTRY']._serialized_start=416
  _globals['_LOGENTRY']._serialized_end=453
  _globals['_EMPTY']._serialized_start=455
  _globals['_EMPTY']._serialized_end=462
  _globals['_RAFTNODE']._serialized_start=464
  _globals['_RAFTNODE']._serialized_end=510
# @@protoc_insertion_point(module_scope)
