# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"5\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x03\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x99\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\x03\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\":\n\x15\x41ppendEntriesResponse\x12\x10\n\x08\x63urrTerm\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\t\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x03\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\"\n\x0fServeClientArgs\x12\x0f\n\x07Request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x10\n\x08LeaderID\x18\x02 \x01(\t\x12\x0f\n\x07Success\x18\x03 \x01(\x08\x32\xbb\x01\n\x0bRaftService\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\x12\x32\n\x0bServeClient\x12\x10.ServeClientArgs\x1a\x11.ServeClientReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGENTRY']._serialized_start=14
  _globals['_LOGENTRY']._serialized_end=67
  _globals['_APPENDENTRIESREQUEST']._serialized_start=70
  _globals['_APPENDENTRIESREQUEST']._serialized_end=223
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=225
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=283
  _globals['_REQUESTVOTEREQUEST']._serialized_start=285
  _globals['_REQUESTVOTEREQUEST']._serialized_end=388
  _globals['_REQUESTVOTERESPONSE']._serialized_start=390
  _globals['_REQUESTVOTERESPONSE']._serialized_end=447
  _globals['_SERVECLIENTARGS']._serialized_start=449
  _globals['_SERVECLIENTARGS']._serialized_end=483
  _globals['_SERVECLIENTREPLY']._serialized_start=485
  _globals['_SERVECLIENTREPLY']._serialized_end=552
  _globals['_RAFTSERVICE']._serialized_start=555
  _globals['_RAFTSERVICE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
